'use client'
import { useState } from 'react'
import { toast } from 'sonner'
export function CollaborationOpportunitySettings({ campaignId, initial, canEdit }: { campaignId: string; initial?: Record<string, unknown> | null; canEdit: boolean }) {
  const [form, setForm] = useState({ enabled: Boolean(initial?.enabled), benefits: String(initial?.benefits ?? ''), participation_value: String(initial?.participation_value ?? ''), seats: String(initial?.seats ?? ''), application_deadline: String(initial?.application_deadline ?? '') })
  const [saving, setSaving] = useState(false)
  if (!canEdit) return null
  async function save() { setSaving(true); try { const res = await fetch(`/api/campaigns/${campaignId}/collaboration-opportunity`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const json = await res.json(); if (!res.ok) throw new Error(json.error); toast.success('Oportunidad guardada') } catch (e) { toast.error(e instanceof Error ? e.message : 'No se pudo guardar') } finally { setSaving(false) } }
  return <section className="card border-violet-100 p-5"><label className="flex cursor-pointer items-center gap-3"><input type="checkbox" checked={form.enabled} onChange={e => setForm({ ...form, enabled: e.target.checked })} className="h-4 w-4 accent-violet-600" /><span><span className="block text-sm font-semibold text-gray-900">Permitir marcas colaboradoras</span><span className="text-xs text-gray-500">Las marcas postulan; Admin aprueba y se activan solo después del pago.</span></span></label>{form.enabled && <div className="mt-4 grid gap-3 md:grid-cols-2"><textarea value={form.benefits} onChange={e => setForm({ ...form, benefits: e.target.value })} placeholder="Beneficios para la marca colaboradora" className="input-base min-h-20 md:col-span-2" /><input value={form.participation_value} onChange={e => setForm({ ...form, participation_value: e.target.value })} type="number" min="0" placeholder="Valor de participación (CLP)" className="input-base" /><input value={form.seats} onChange={e => setForm({ ...form, seats: e.target.value })} type="number" min="0" placeholder="Cupos disponibles" className="input-base" /><input value={form.application_deadline} onChange={e => setForm({ ...form, application_deadline: e.target.value })} type="datetime-local" className="input-base md:col-span-2" /></div>}<button disabled={saving} onClick={save} className="mt-4 rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Guardando…' : 'Guardar'}</button></section>
}
