'use client'

import { useMemo, useState } from 'react'
import { BookOpenCheck, ChevronRight, FileCode2, FileText, Filter, Folder, FolderOpen, Layers3, Search, ShieldCheck, TestTube2, Wrench } from 'lucide-react'
import { cn } from '@/lib/utils'
import { RequirementPilot } from './RequirementPilot'

type Status = 'implementado' | 'parcial' | 'pendiente' | 'verificar'
type Requirement = {
  id: string
  portal: 'Admin' | 'Marca' | 'Influencer' | 'Plataforma'
  module: string
  title: string
  behavior: string
  rules: string
  acceptance: string[]
  status: Status
  evidence: string[]
  documentation: string
  tests: string
  gaps: string
}

const STATUS: Record<Status, { label: string; className: string }> = {
  implementado: { label: 'Implementado', className: 'bg-emerald-50 text-emerald-700 ring-emerald-600/15' },
  parcial: { label: 'Parcial', className: 'bg-amber-50 text-amber-700 ring-amber-600/15' },
  pendiente: { label: 'Pendiente', className: 'bg-slate-100 text-slate-600 ring-slate-500/15' },
  verificar: { label: 'Por verificar', className: 'bg-sky-50 text-sky-700 ring-sky-600/15' },
}
const DOC = 'docs/FUNCTIONAL_DESIGN.md'
const FDD = 'docs/SCENCE_FDD_v2.2.md'
const r = (item: Requirement) => item

// Registro funcional atómico. “Implementado” exige evidencia de código y fuente documental.
const REQUIREMENTS: Requirement[] = [
  r({ id: 'DASH-001', portal: 'Admin', module: 'Dashboard', title: 'Visualizar KPI real de influencers activos', behavior: 'Muestra el número de influencers activos del roster SCENCE.', rules: 'Cuenta influencers is_active=true del organization_id actual. La definición aprobada, el historial y las evidencias del piloto viven en la base de datos.', acceptance: ['Excluye influencers inactivos.', 'Coincide con el agregado de /api/dashboard.', 'La validación en datos reales queda registrada antes de declararlo validado.'], status: 'verificar', evidence: ['src/app/api/dashboard/route.ts · GET, count con is_active=true', 'src/app/(dashboard)/DashboardClient.tsx · KpiCard', 'src/app/api/admin/requirements/[key]/route.ts · versiones e historial'], documentation: `${DOC} §3.1 AD-01; ${FDD} §3.1 AD-01`, tests: 'tests/requirements-dashboard-kpi.test.ts; falta validación con datos reales de desarrollo.', gaps: 'Aplicar migración solo en entorno autorizado y ejecutar validación del KPI contra datos reales.' }),
  r({ id: 'DASH-002', portal: 'Admin', module: 'Dashboard', title: 'Visualizar campañas operativas', behavior: 'Muestra el total de campañas en curso del Admin.', rules: 'Se limita a organization_id de la sesión y a los estados operativos que calcula el backend.', acceptance: ['El KPI carga desde /api/dashboard.', 'Campañas de otra organización no cambian el total.'], status: 'implementado', evidence: ['src/app/api/dashboard/route.ts · GET, agregado campaigns', 'src/app/(dashboard)/DashboardClient.tsx · KpiCard'], documentation: `${DOC} §3.1 AD-01; ${FDD} §3.1 AD-01`, tests: 'Sin prueba unitaria específica; validar respuesta de /api/dashboard.', gaps: 'QA visual con datos reales pendiente.' }),
  r({ id: 'DASH-003', portal: 'Admin', module: 'Dashboard', title: 'Visualizar marcas pendientes de aprobación', behavior: 'Muestra contador y enlace a marcas pendientes.', rules: 'El enlace usa status=pending_approval y no expone marcas de otra organización.', acceptance: ['El contador aparece cuando hay pendientes.', 'El enlace abre el listado filtrado.'], status: 'implementado', evidence: ['src/app/(dashboard)/DashboardClient.tsx · pendingBrands', 'src/components/layout/Sidebar.tsx · navigation summary'], documentation: `${DOC} §3.1 AD-01 y AD-09`, tests: 'Sin prueba específica identificada.', gaps: 'Validar contador y enlace manualmente.' }),
  r({ id: 'DASH-004', portal: 'Admin', module: 'Dashboard', title: 'Visualizar facturación mensual', behavior: 'Muestra facturación del período en el Dashboard.', rules: 'Deriva de invoices de la organización; referencia monetaria CLP.', acceptance: ['Se formatea como moneda.', 'No incluye invoices de otra organización.'], status: 'implementado', evidence: ['src/app/api/dashboard/route.ts · agregado invoices', 'src/app/(dashboard)/DashboardClient.tsx · KPI financiero'], documentation: `${DOC} §3.1 AD-01; ${DOC} §2 BR-01/BR-09`, tests: 'Sin prueba específica identificada.', gaps: 'QA con facturas vacías, pagadas y vencidas.' }),
  r({ id: 'DASH-005', portal: 'Admin', module: 'Dashboard', title: 'Calcular margen operativo', behavior: 'Muestra margen a partir de facturación y payroll.', rules: 'Usa valores financieros del mismo alcance organizacional.', acceptance: ['Con datos presenta un valor.', 'Sin datos no muestra NaN.'], status: 'implementado', evidence: ['src/app/api/dashboard/route.ts · invoices/payroll_runs', 'src/app/(dashboard)/DashboardClient.tsx · KPI margen'], documentation: `${DOC} §3.1 AD-01`, tests: 'Sin prueba específica identificada.', gaps: 'Revisar cálculo contra cierre contable.' }),
  r({ id: 'DASH-006', portal: 'Admin', module: 'Dashboard', title: 'Personalizar widgets del Dashboard', behavior: 'Permite agregar, quitar o reordenar widgets.', rules: 'No hay configuración de widgets documentada ni código de persistencia identificado.', acceptance: ['No se declara lista sin UI y persistencia.', 'Una futura solución define alcance por usuario u organización.'], status: 'pendiente', evidence: ['src/app/(dashboard)/DashboardClient.tsx · no hay registro ni controles de widgets'], documentation: `${DOC} §3.1 AD-01 · no especifica esta capacidad`, tests: 'No existen pruebas.', gaps: 'Requiere decisión de producto, diseño de persistencia y pruebas.' }),

  r({ id: 'CAMP-001', portal: 'Admin', module: 'Campañas', title: 'Listar campañas de la organización', behavior: 'Muestra campañas operativas y permite abrir su detalle.', rules: 'La consulta se delimita por organization_id.', acceptance: ['Carga campañas de la organización actual.', 'Cada fila abre el ID correcto.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-campaigns/CampaignsClient.tsx', 'src/app/api/campaigns/route.ts · GET'], documentation: `${DOC} §3.1 AD-02; ${DOC} §2 BR-01`, tests: 'tests/campaign-list-order.test.ts.', gaps: 'QA de paginación y estados.' }),
  r({ id: 'CAMP-002', portal: 'Admin', module: 'Campañas', title: 'Filtrar campañas por criterios operativos', behavior: 'Filtra por búsqueda, tipo, plataforma, fecha y estado.', rules: 'Los query params no amplían el alcance organizacional.', acceptance: ['Cambiar filtro actualiza la lista.', 'Reset restaura la lista base.'], status: 'implementado', evidence: ['src/components/campaigns/CampaignFilters.tsx · CampaignFilters', 'src/app/api/campaigns/route.ts · GET'], documentation: `${DOC} §3.1 AD-02`, tests: 'Sin prueba de filtros específica.', gaps: 'Agregar prueba de integración de query params.' }),
  r({ id: 'CAMP-003', portal: 'Admin', module: 'Campañas', title: 'Crear una campaña en borrador', behavior: 'Crea una campaña inicial desde el wizard.', rules: 'Valida campos requeridos y asigna status=draft.', acceptance: ['Formulario válido crea draft.', 'Formulario inválido no persiste.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-campaigns/new/CampaignForm.tsx · CampaignForm', 'src/app/api/campaigns/route.ts · POST'], documentation: `${DOC} §3.1 AD-03; ${DOC} §14 C.2`, tests: 'Sin prueba de creación específica.', gaps: 'QA E2E del wizard.' }),
  r({ id: 'CAMP-004', portal: 'Admin', module: 'Campañas', title: 'Definir visibilidad privada u abierta', behavior: 'Permite seleccionar private u open para la campaña.', rules: 'private usa invitación; open usa postulación; valores válidos: private/open.', acceptance: ['Private no se ofrece como abierta.', 'Open se ofrece al flujo autorizado de postulación.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-campaigns/new/CampaignForm.tsx · visibility', 'src/app/api/influencer/campaigns/open/route.ts · visibility=open'], documentation: `${DOC} §2 BR-03; ${DOC} §3.1 AD-03`, tests: 'tests/campaign-applications-auth.test.ts.', gaps: 'Revalidar creación open y postulación E2E.' }),
  r({ id: 'CAMP-005', portal: 'Admin', module: 'Campañas', title: 'Aprobar o rechazar un deliverable', behavior: 'Permite revisar, calificar y aprobar o rechazar una entrega.', rules: 'Solo se revisan entregables con URL; aplica el ciclo de estados de deliverables.', acceptance: ['Un deliverable in_review se aprueba o rechaza.', 'La calificación queda en el deliverable correcto.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-campaigns/[id]/CampaignDetail.tsx · Deliverables', 'src/app/api/campaign-deliverables/[id]/route.ts · PATCH'], documentation: `${DOC} §3.1 AD-04; ${DOC} §5`, tests: 'Sin prueba directa identificada.', gaps: 'Agregar transición rejected → in_review.' }),
  r({ id: 'CAMP-006', portal: 'Admin', module: 'Campañas', title: 'Notificar el siguiente batch de campaña abierta', behavior: 'Envía manualmente el siguiente lote a influencers elegibles.', rules: 'Solo Admin y campañas open; máximo 50, orden por seguidores y sin repetir destinatarios.', acceptance: ['No notifica dos veces a la misma persona para la campaña.', 'Marca no muestra esta acción.'], status: 'implementado', evidence: ['src/app/api/campaigns/[id]/notify-influencers/route.ts · POST', 'src/lib/campaign-notifications.ts · announceCampaignToInfluencers'], documentation: `${DOC} §3.1 AD-04; ${DOC} §9 EMAIL-05`, tests: 'Sin prueba específica.', gaps: 'Prueba de integración de correo en entorno seguro.' }),
  r({ id: 'CAMP-007', portal: 'Plataforma', module: 'Campañas', title: 'Crear deliverables al aceptar una asignación', behavior: 'Crea entregables desde el template al aceptar invitación o postulación.', rules: 'El primer aceptado activa la campaña; cada deliverable genera tarea vinculada.', acceptance: ['Aceptar crea los entregables de plantilla.', 'No crea tareas genéricas sin deliverable.'], status: 'implementado', evidence: ['src/lib/campaign-deliverables-sync.ts · syncCampaignDeliverablesFromTemplates', 'src/lib/campaign-applications.ts · acceptCampaignApplication'], documentation: `${DOC} §2 BR-04/BR-07`, tests: 'tests/campaign-applications-auth.test.ts.', gaps: 'Confirmar cobertura unitaria del sync antes de modificarlo.' }),
  r({ id: 'CAMP-008', portal: 'Plataforma', module: 'Campañas', title: 'Mantener inmutable deliverables_spec de invitación', behavior: 'Conserva la especificación aceptada como contrato informal.', rules: 'No debe modificarse tras crear invitación; campaign_deliverables es fuente operacional.', acceptance: ['Un cambio posterior no sobrescribe deliverables_spec.', 'Los entregables mantienen trazabilidad.'], status: 'verificar', evidence: ['src/app/api/brand/campaigns/[id]/invite/route.ts · creación', 'src/lib/campaign-deliverables-sync.ts'], documentation: `${DOC} §2 BR-05`, tests: 'No se identificó prueba dedicada.', gaps: 'Auditar PATCHs de campaign_influencers y crear regresión antes de declararlo implementado.' }),

  r({ id: 'INF-001', portal: 'Admin', module: 'Influencers', title: 'Consultar roster con campos administrativos', behavior: 'Muestra identidad, redes, métricas y contacto del roster.', rules: 'Contacto y tarifas históricas son solo Admin.', acceptance: ['La lista carga el roster.', 'Marca no recibe campos restringidos.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-influencers/InfluencersClient.tsx', 'src/components/influencers/InfluencerTable.tsx', 'src/app/api/influencers/route.ts · GET'], documentation: `${DOC} §3.1 AD-05; ${DOC} §2 BR-06`, tests: 'Sin prueba de UI específica.', gaps: 'QA de columnas visibles por portal.' }),
  r({ id: 'INF-002', portal: 'Admin', module: 'Influencers', title: 'Ordenar y configurar columnas del roster', behavior: 'Ordena la tabla y guarda columnas/ancho elegidos.', rules: 'Las preferencias son locales y no alteran datos de roster.', acceptance: ['Click en header cambia orden.', 'Preferencia persiste al recargar.'], status: 'implementado', evidence: ['src/components/ui/SortableTH.tsx', 'src/components/ui/ColumnVisibilityMenu.tsx', 'src/hooks/useColumnWidths.ts'], documentation: `${DOC} §3.1 AD-05`, tests: 'Sin prueba específica.', gaps: 'Agregar prueba de persistencia.' }),
  r({ id: 'INF-003', portal: 'Admin', module: 'Influencers', title: 'Detectar duplicados de influencers', behavior: 'Detecta grupos duplicados por email, URL o handle Instagram.', rules: 'La detección ocurre server-side antes de saneamiento.', acceptance: ['Un duplicado aparece en reporte.', 'Un registro único no se marca.'], status: 'implementado', evidence: ['src/lib/influencers/dataQuality.ts · findDuplicates', 'src/app/api/influencers/duplicates/route.ts · GET'], documentation: `${DOC} §3.1 AD-07; ${DOC} §4 REP-04`, tests: 'Cobertura relacionada en tests de calidad de influencers.', gaps: 'Documentar casos límite de handles.' }),
  r({ id: 'INF-004', portal: 'Admin', module: 'Influencers', title: 'Fusionar influencers duplicados', behavior: 'Fusiona registros duplicados por el flujo autorizado.', rules: 'Preserva relaciones y aplica protecciones de historial/Pro.', acceptance: ['Una fusión autorizada conserva relaciones.', 'Una bloqueada no elimina datos.'], status: 'implementado', evidence: ['src/lib/influencers/hardDelete.ts · protecciones', 'src/app/api/influencers/merge/route.ts · POST'], documentation: `${DOC} §3.1 AD-07`, tests: 'tests/influencer-pro-integrity.test.ts.', gaps: 'QA con duplicado real antes de cambiar lógica.' }),
  r({ id: 'INF-005', portal: 'Admin', module: 'Influencers', title: 'Sincronizar métricas de Instagram', behavior: 'Actualiza followers y estado de perfiles bajo demanda.', rules: 'Errores, rate limits o token ausente no sobrescriben métricas válidas.', acceptance: ['Respuesta válida actualiza followers y synced_at.', 'Error conserva datos y libera locks.'], status: 'implementado', evidence: ['src/lib/instagram/followers-sync.ts · syncInstagramFollowers', 'src/lib/instagram/business-discovery.ts · buildSyncPatch', 'src/app/api/influencers/sync-instagram/route.ts'], documentation: `${DOC} §3.1 AD-07; ${DOC} §6 INT-02`, tests: 'tests/instagram-followers-sync.test.ts.', gaps: 'Depende de configuración externa Meta/Apify.' }),
  r({ id: 'INF-006', portal: 'Admin', module: 'Influencers', title: 'Ordenar influencers por desempeño', behavior: 'Muestra ranking por seguidores, engagement, rating y cumplimiento.', rules: 'Usa métricas de perfil y desempeño disponible.', acceptance: ['Cambiar criterio cambia orden.', 'No se recorta por límite menor al roster soportado.'], status: 'implementado', evidence: ['src/lib/influencers/ranking.ts · buildRankingRows/sortRankingRows', 'src/components/influencers/InfluencerRanking.tsx', 'src/app/api/influencers/ranking/route.ts'], documentation: `${DOC} §3.1 AD-08; ${DOC} §4 REP-03`, tests: 'Sin prueba específica.', gaps: 'QA sobre roster completo.' }),

  r({ id: 'BRAND-001', portal: 'Admin', module: 'Marcas', title: 'Aprobar o suspender una marca', behavior: 'Cambia el estado operativo de la marca.', rules: 'El estado actúa como gate de acceso al portal Marca.', acceptance: ['Actualiza solo la marca elegida.', 'Una suspendida no obtiene acceso indebido.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-brands/[id]/page.tsx', 'src/app/api/brands/[id]/route.ts · PATCH'], documentation: `${DOC} §3.1 AD-09`, tests: 'Sin prueba específica.', gaps: 'QA de transición y sesión iniciada.' }),
  r({ id: 'BRAND-002', portal: 'Marca', module: 'Campañas de Marca', title: 'Ver únicamente campañas propias', behavior: 'Consulta campañas de su relación autorizada.', rules: 'No lee campañas ajenas; colaboradoras respetan alcance permitido.', acceptance: ['API no devuelve campaña ajena.', 'UI no ofrece acceso indebido.'], status: 'implementado', evidence: ['src/app/api/brand/campaigns/route.ts · GET', 'src/lib/campaign-brand-access.ts · authorizeCampaignBrandAction'], documentation: `${DOC} §3.2 MK-01/MK-02; ${DOC} §2 BR-06`, tests: 'tests/campaign-collaborations-auth.test.ts.', gaps: 'Revisar permisos al ampliar colaboraciones.' }),
  r({ id: 'BRAND-003', portal: 'Marca', module: 'Campañas de Marca', title: 'Crear campaña ligada a marca autenticada', behavior: 'Crea campaña desde wizard compartido.', rules: 'brand_id y created_by_brand_id derivan de sesión; el plan puede limitar.', acceptance: ['La campaña queda ligada a la marca autenticada.', 'Cliente no puede inyectar otro brand_id.'], status: 'implementado', evidence: ['src/components/campaigns/CampaignFormView.tsx', 'src/app/api/brand/campaigns/route.ts · POST'], documentation: `${DOC} §3.2 MK-03; ${DOC} §2 BR-10`, tests: 'tests/brand-plan-access.test.ts.', gaps: 'QA E2E de límite por plan.' }),
  r({ id: 'BRAND-004', portal: 'Marca', module: 'Campañas de Marca', title: 'Invitar influencer a campaña propia', behavior: 'Crea invitación con tarifa, mensaje y entregables.', rules: 'Campaña debe ser propia; deliverables_spec es inmutable; email no bloquea creación.', acceptance: ['La invitación válida se crea.', 'Fallo de email no borra invitación.'], status: 'implementado', evidence: ['src/app/api/brand/campaigns/[id]/invite/route.ts · POST', 'src/lib/resend.ts · influencerInviteEmail'], documentation: `${DOC} §3.2 MK-05; ${DOC} §2 BR-05; ${DOC} §9 EMAIL-01`, tests: 'Sin prueba de fallo no bloqueante.', gaps: 'Agregar prueba simulando fallo de Resend.' }),
  r({ id: 'BRAND-005', portal: 'Marca', module: 'Influencers de Marca', title: 'Ocultar datos privados del roster a Marca', behavior: 'Expone solo influencers relacionados y campos permitidos.', rules: 'No entrega roster global, notas, contacto ni tarifas históricas.', acceptance: ['API no devuelve campos restringidos.', 'UI no muestra Data Quality.'], status: 'implementado', evidence: ['src/app/api/brand/influencers/route.ts', 'src/app/(brand)/brand-influencers/page.tsx', 'src/lib/brand-permissions.ts'], documentation: `${DOC} §3.2 MK-07; ${DOC} §2 BR-06`, tests: 'tests/campaign-collaborations-auth.test.ts.', gaps: 'No existe perfil público individual (G-09).' }),
  r({ id: 'BRAND-006', portal: 'Marca', module: 'Perfil de Marca', title: 'Exigir Instagram al completar perfil', behavior: 'Bloquea uso operativo si falta Instagram de la marca.', rules: 'Layout redirige a perfil y API no permite vaciar el campo.', acceptance: ['Sin Instagram redirige a completar.', 'PATCH no permite eliminarlo.'], status: 'implementado', evidence: ['src/app/(brand)/layout.tsx · gate', 'src/app/api/brand/me/route.ts · PATCH'], documentation: `${DOC} §3.2 · nota Instagram obligatorio`, tests: 'Sin prueba específica.', gaps: 'QA de registro y primer login.' }),
  r({ id: 'BRAND-007', portal: 'Marca', module: 'Facturación de Marca', title: 'Consultar billing operativo de marca', behavior: 'Permite ver facturas y documentos tributarios con SCENCE.', rules: 'No confundir billing operativo con plan SaaS.', acceptance: ['No se declara listo sin historial real.', 'Plan continúa separado de billing.'], status: 'pendiente', evidence: ['src/app/(brand)/brand-billing/page.tsx · placeholder', 'src/components/plan/BrandPlanSettings.tsx · plan'], documentation: `${DOC} §3.2 MK-12b; ${DOC} §2.4`, tests: 'No hay pruebas de billing operativo.', gaps: 'Falta definición de documentos, datos y autorización.' }),
  r({ id: 'BRAND-008', portal: 'Marca', module: 'Colaboraciones', title: 'Ver marcas colaboradoras solo por nombre', behavior: 'Muestra otras marcas relacionadas sin información sensible.', rules: 'Alcance exacto pendiente de decisión de producto.', acceptance: ['No se expone información comercial sin decisión.', 'Al habilitarse se limita al nombre permitido.'], status: 'pendiente', evidence: ['src/app/(brand)/brand-brands/page.tsx', 'src/components/campaigns/CollaboratingBrandsTab.tsx'], documentation: `${DOC} §3.2 MK-13; ${DOC} §2 BR-06`, tests: 'No hay pruebas de alcance pendiente.', gaps: 'Falta decisión explícita de producto.' }),

  r({ id: 'CRE-001', portal: 'Influencer', module: 'Campañas', title: 'Ver campañas asignadas al influencer', behavior: 'Muestra campañas con asignación aceptada.', rules: 'Solo filas vinculadas al influencer autenticado.', acceptance: ['Una aceptada aparece al dueño.', 'Otro influencer no puede verla.'], status: 'implementado', evidence: ['src/app/(influencer)/inf-campaigns/page.tsx', 'src/app/api/influencer/campaigns/route.ts · GET'], documentation: `${DOC} §3.3 IN-03; ${DOC} §14 C.1`, tests: 'Sin prueba específica.', gaps: 'QA de estados accepted/pending/completed.' }),
  r({ id: 'CRE-002', portal: 'Influencer', module: 'Campañas', title: 'Postular a campaña abierta', behavior: 'Envía postulación a campaña open elegible.', rules: 'Solo open de la organización; usa application_status.', acceptance: ['Crea estado pending.', 'No postula a private o campaña ajena.'], status: 'implementado', evidence: ['src/app/api/influencer/campaigns/[id]/apply/route.ts · POST', 'src/app/api/influencer/campaigns/open/route.ts · GET', 'src/components/campaigns/ApplyConfirmDialog.tsx'], documentation: `${DOC} §2 BR-03; ${DOC} §14 C.1`, tests: 'tests/campaign-applications-auth.test.ts.', gaps: 'UI de invitaciones separada sigue como G-01.' }),
  r({ id: 'CRE-003', portal: 'Influencer', module: 'Entregables', title: 'Ver solo tareas y entregables propios', behavior: 'Muestra checklist personal y entregables vinculados.', rules: 'Filtra por influencer autenticado; tarea de campaña enlaza por deliverable_id.', acceptance: ['No aparecen tareas de otra persona.', 'Tarea muestra contexto del deliverable.'], status: 'implementado', evidence: ['src/app/(influencer)/inf-deliverables/page.tsx', 'src/app/api/influencer/tasks/route.ts · GET'], documentation: `${DOC} §3.3 IN-02; ${DOC} §2 BR-04`, tests: 'Sin prueba específica.', gaps: 'Revisar autorización por task ID.' }),
  r({ id: 'CRE-004', portal: 'Influencer', module: 'Entregables', title: 'Entregar contenido por URL y notas', behavior: 'Permite enviar URL y notas para deliverable asignado.', rules: 'La entrega debe pertenecer al influencer y entra al ciclo de revisión.', acceptance: ['Entrega propia pasa a revisión.', 'No se entrega por ID ajeno.'], status: 'implementado', evidence: ['src/app/api/influencer/deliverables/[id]/submit/route.ts · POST', 'src/app/(influencer)/inf-deliverables/page.tsx'], documentation: `${DOC} §3.3 IN-02; ${DOC} §5`, tests: 'Sin prueba específica.', gaps: 'Agregar prueba de autorización y transición.' }),
  r({ id: 'CRE-005', portal: 'Influencer', module: 'Bookings', title: 'Consultar booking con marca correcta', behavior: 'Muestra booking, campaña y marca vinculada.', rules: 'Relación correcta: booking → campaign → brand; no hay FK directa a brands.', acceptance: ['Booking muestra marca de su campaña.', 'Consulta no usa join inexistente.'], status: 'implementado', evidence: ['src/app/(influencer)/inf-bookings/page.tsx', 'src/app/api/influencer/bookings/route.ts · GET'], documentation: `${DOC} §3.3 IN-05; ${DOC} §12 B-06`, tests: 'Sin prueba específica.', gaps: 'QA de booking sin campaña/marca.' }),
  r({ id: 'CRE-006', portal: 'Influencer', module: 'Perfil', title: 'Exigir perfil completo antes de operar', behavior: 'Bloquea navegación si faltan Instagram, comuna o dirección.', rules: 'Validación en layout y servidor; datos privados solo para dueño/Admin.', acceptance: ['Perfil incompleto redirige.', 'PATCH no deja campos obligatorios incompletos.'], status: 'implementado', evidence: ['src/app/(influencer)/layout.tsx · ProfileCompletionGate', 'src/app/api/influencer/me/route.ts · PATCH'], documentation: `${DOC} §3.3 IN-06; ${DOC} §2 BR-06`, tests: 'Sin prueba específica.', gaps: 'QA de cada campo y redirect.' }),

  r({ id: 'BOOK-001', portal: 'Admin', module: 'Bookings', title: 'Gestionar agenda operativa de bookings', behavior: 'Permite consultar y administrar bookings de la organización.', rules: 'Un booking se relaciona con su campaña; las confirmaciones siguen su propio flujo.', acceptance: ['GET devuelve bookings de la organización.', 'Crear, actualizar o borrar opera sobre el booking autorizado.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-bookings/BookingsClient.tsx', 'src/app/api/bookings/route.ts · GET/POST/PUT/DELETE'], documentation: `${DOC} §3.1 AD-10`, tests: 'tests/attendance-expiration.test.ts cubre vencimientos relacionados.', gaps: 'QA de agenda mensual y edición manual.' }),
  r({ id: 'BOOK-002', portal: 'Admin', module: 'Bookings', title: 'Sincronizar booking con Google Calendar', behavior: 'Crea, actualiza o elimina un evento de calendario asociado al booking.', rules: 'Depende de Service Account y de la UX expuesta; no debe fallar silenciosamente ni alterar otro booking.', acceptance: ['Una operación autorizada llama al adaptador correcto.', 'Fallo de Calendar se informa y no corrompe el booking.'], status: 'parcial', evidence: ['src/lib/google-calendar.ts · createCalendarEvent/updateCalendarEvent/deleteCalendarEvent', 'src/app/api/bookings/route.ts'], documentation: `${DOC} §3.1 AD-10; ${DOC} §6 INT-01; docs/IMPLEMENTATION_ROADMAP.md §3`, tests: 'Sin prueba específica de Calendar.', gaps: 'El roadmap señala UI/UX de Calendar no expuesta completamente; requiere QA con cuenta de servicio.' }),
  r({ id: 'ANL-001', portal: 'Admin', module: 'Analytics', title: 'Consultar métricas ejecutivas por período', behavior: 'Muestra revenue, margen, budget utilizado y completion para un rango seleccionado.', rules: 'Los datos se agregan por período y organización.', acceptance: ['Cambiar rango actualiza métricas.', 'El resultado no incluye datos de otra organización.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-analytics/AnalyticsClient.tsx', 'src/app/api/analytics/route.ts · GET'], documentation: `${DOC} §3.1 AD-15; ${DOC} §4 REP-02`, tests: 'Sin prueba específica identificada.', gaps: 'Export y filtros avanzados figuran como pendientes en el roadmap.' }),

  r({ id: 'FIN-001', portal: 'Admin', module: 'Facturación', title: 'Calcular IVA de factura en Chile', behavior: 'Calcula tax_amount usando IVA 19%.', rules: 'tax_amount = subtotal * 0.19; moneda por defecto CLP.', acceptance: ['Subtotal conocido calcula IVA 19%.', 'Total incorpora impuesto.'], status: 'implementado', evidence: ['src/app/api/invoices/route.ts · POST', 'src/app/(dashboard)/admin-billing/BillingClient.tsx'], documentation: `${DOC} §2 BR-08/BR-09; ${DOC} §3.1 AD-11`, tests: 'Sin prueba aislada de IVA.', gaps: 'Agregar prueba de redondeo CLP.' }),
  r({ id: 'FIN-002', portal: 'Admin', module: 'Payroll', title: 'Gestionar estados de payroll', behavior: 'Permite revisar y actualizar el ciclo de payroll.', rules: 'Transiciones: pending → approved → processing → paid/failed.', acceptance: ['Transición válida persiste.', 'Inválida no deja estado inconsistente.'], status: 'implementado', evidence: ['src/app/api/payroll/route.ts · GET/POST/PATCH', 'src/app/(dashboard)/admin-billing/BillingClient.tsx'], documentation: `${DOC} §3.1 AD-11; ${DOC} §14 C.2`, tests: 'Sin prueba específica.', gaps: 'Agregar pruebas de máquina de estados.' }),
  r({ id: 'CON-001', portal: 'Admin', module: 'Contratos', title: 'Generar contrato con variables de campaña', behavior: 'Resuelve variables desde campaña y colaboración autorizada.', rules: 'No inventa marca ni monto cuando contexto es incompleto.', acceptance: ['Colaboración confirmada produce contexto.', 'Datos incompletos fallan de forma controlada.'], status: 'implementado', evidence: ['src/lib/contract-render.ts · buildCampaignContractContext', 'src/lib/contract-from-collaboration.ts · resolveCollaborationContractTerms', 'src/app/api/contracts/route.ts'], documentation: `${DOC} §3.1 AD-12`, tests: 'tests/contract-from-collaboration.test.ts; tests/contract-render-address.test.ts.', gaps: 'QA de plantilla desde interfaz.' }),
  r({ id: 'CRM-001', portal: 'Admin', module: 'CRM', title: 'Buscar y calificar un prospecto', behavior: 'Busca leads y modifica su estado de calificación.', rules: 'CRM aislado de brands, influencers, campaigns y auth.', acceptance: ['Filtro reduce lista.', 'Calificación queda en lead correcto.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-crm/CrmLeadsClient.tsx', 'src/app/api/crm-leads/route.ts · GET/PATCH'], documentation: `${DOC} §3.1 AD-18`, tests: 'Pruebas de guardas de envío CRM.', gaps: 'Dataset histórico solo tiene emails poblados según FDD.' }),
  r({ id: 'CRM-002', portal: 'Admin', module: 'CRM', title: 'Evitar envío duplicado a un lead', behavior: 'Reserva el lead antes del envío comercial.', rules: 'Error ambiguo conserva reserva y no reenvía automáticamente.', acceptance: ['Dos procesos envían como máximo uno.', '5xx no dispara reintento inseguro.'], status: 'implementado', evidence: ['src/lib/crm-send-guard.ts · claimLeadSend/processLeadBatch', 'src/app/api/crm-leads/[id]/send-intro/route.ts'], documentation: `${DOC} §3.1 AD-18; ${DOC} §9`, tests: 'tests/crm-send-guard.test.ts; tests/crm-bulk-send-guard.test.ts.', gaps: 'Revisar envío real solo con autorización.' }),
  r({ id: 'CRM-003', portal: 'Admin', module: 'CRM', title: 'Reimportar dataset CRM completo', behavior: 'Importa CSV origen con empresa, región e industria bien mapeadas.', rules: 'No sobrescribe datos sin CSV validado y proceso reproducible.', acceptance: ['Mapea columnas acordadas.', 'Valida conteos de importación.'], status: 'pendiente', evidence: ['docs/IMPLEMENTATION_ROADMAP.md · estado CRM', 'docs/FUNCTIONAL_DESIGN.md §3.1 AD-18 · datos incompletos'], documentation: `${DOC} §3.1 AD-18; docs/IMPLEMENTATION_ROADMAP.md §3`, tests: 'No hay prueba reproducible: CSV no está en repo.', gaps: 'Falta CSV fuente y plan de importación aprobado.' }),
  r({ id: 'EVT-001', portal: 'Admin', module: 'Eventos', title: 'Gestionar eventos y entradas', behavior: 'Consulta eventos y administra tickets y ventas.', rules: 'Tickets y ventas pertenecen al event ID solicitado.', acceptance: ['La lista abre el evento correcto.', 'Rutas consultan por event ID.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-events/page.tsx', 'src/app/api/events/route.ts', 'src/app/api/events/[id]/tickets/route.ts', 'src/app/api/events/[id]/sales/route.ts'], documentation: `${DOC} §3.1 AD-14`, tests: 'Sin prueba específica.', gaps: 'QA de ticket y venta.' }),
  r({ id: 'AFF-001', portal: 'Admin', module: 'Afiliados', title: 'Atribuir clicks a un link de afiliado', behavior: 'Resuelve código de tracking y registra navegación atribuida.', rules: 'Código identifica un link; conversiones se asocian al mismo link.', acceptance: ['Código válido redirige.', 'Código inválido no crea atribución.'], status: 'implementado', evidence: ['src/app/api/track/[code]/route.ts · GET', 'src/app/api/affiliates/route.ts · GET/POST'], documentation: `${DOC} §3.1 AD-13`, tests: 'Sin prueba específica.', gaps: 'Agregar pruebas de código inexistente y atribución.' }),
  r({ id: 'SUP-001', portal: 'Admin', module: 'Soporte', title: 'Gestionar estado de un ticket', behavior: 'Triagea tickets abiertos, en progreso o cerrados.', rules: 'Respuestas y cambios se asocian al ticket de la organización.', acceptance: ['Cambio persiste en ticket elegido.', 'Ticket ajeno no aparece.'], status: 'implementado', evidence: ['src/components/support/SupportPage.tsx · SupportPage', 'src/app/api/tickets/[id]/route.ts · PATCH'], documentation: `${DOC} §3.1 AD-16`, tests: 'Sin prueba específica.', gaps: 'Agregar prueba de aislamiento organizacional.' }),
  r({ id: 'SET-001', portal: 'Admin', module: 'Configuración', title: 'Administrar ubicaciones de la organización', behavior: 'Crea, edita y elimina lugares organizacionales.', rules: 'Es org-scoped y solo super_admin puede modificar.', acceptance: ['GET muestra lugares propios.', 'PATCH/DELETE requieren lugar autorizado.'], status: 'implementado', evidence: ['src/app/(dashboard)/admin-settings/locations/page.tsx', 'src/app/api/locations/route.ts · GET/POST', 'src/app/api/locations/[id]/route.ts · PATCH/DELETE'], documentation: `${DOC} §3.1 AD-17; ${DOC} §14 G-13`, tests: 'tests/locations/README.md y pruebas asociadas.', gaps: 'QA de formularios y permisos.' }),
  r({ id: 'AUTH-001', portal: 'Plataforma', module: 'Acceso', title: 'Bloquear acceso cruzado entre portales', behavior: 'Middleware dirige o bloquea rutas según usuario autenticado.', rules: 'Admin, Marca e Influencer usan rutas separadas; UI no reemplaza middleware.', acceptance: ['Marca no abre Admin.', 'Influencer no abre Marca.'], status: 'implementado', evidence: ['src/middleware.ts · ADMIN_ONLY/BRAND_ONLY/INFLUENCER_ONLY', 'src/lib/supabase/ensureOrg.ts · resolveBrandAccess'], documentation: `${DOC} §2 BR-02/BR-11; ${DOC} §8 NFR-05`, tests: 'tests/login-504-resilience.test.ts.', gaps: 'Mantener matriz de rutas al agregar módulos.' }),
  r({ id: 'DATA-001', portal: 'Admin', module: 'Importación', title: 'Importar influencers desde CSV', behavior: 'Carga influencers en lote desde CSV.', rules: 'Máximo 1.500 por lote; crea draft y requiere revisión posterior.', acceptance: ['CSV válido crea drafts.', 'Lote excesivo se rechaza o limita explícitamente.'], status: 'implementado', evidence: ['src/components/influencers/BulkUploadModal.tsx', 'src/app/api/influencers/bulk/route.ts · POST'], documentation: `${DOC} §7 “Importación masiva de influencers”`, tests: 'Sin prueba específica.', gaps: 'Agregar pruebas de límite y CSV.' }),
  r({ id: 'EMAIL-001', portal: 'Plataforma', module: 'Notificaciones', title: 'Enviar email de invitación sin bloquear la invitación', behavior: 'Al crear invitación intenta notificar al influencer.', rules: 'Falta de email o fallo no elimina la invitación creada.', acceptance: ['Invitación persiste si Resend falla.', 'Correo lleva marca, campaña y enlace.'], status: 'implementado', evidence: ['src/app/api/brand/campaigns/[id]/invite/route.ts', 'src/lib/resend.ts · influencerInviteEmail'], documentation: `${DOC} §9 EMAIL-01`, tests: 'Sin prueba de fallo no bloqueante.', gaps: 'Agregar prueba simulando error de proveedor.' }),
  r({ id: 'EMAIL-002', portal: 'Plataforma', module: 'Notificaciones', title: 'Enviar recibo tras confirmar booking', behavior: 'Envía recibo al confirmar asistencia desde el enlace.', rules: 'Solicitud de confirmación y recibo son pasos diferentes.', acceptance: ['Confirmación invoca recibo.', 'No se confunde con solicitud inicial.'], status: 'implementado', evidence: ['src/app/api/bookings/send-confirmations/route.ts', 'src/app/api/bookings/confirm/route.ts', 'src/lib/resend.ts · bookingConfirmEmail'], documentation: `${DOC} §9 EMAIL-02`, tests: 'Sin prueba específica.', gaps: 'Prueba de integración de enlaces firmados.' }),
  r({ id: 'INT-001', portal: 'Plataforma', module: 'Pagos', title: 'Cobrar suscripción de Marca mediante Stripe live', behavior: 'Procesa cobros reales y concilia suscripciones.', rules: 'No se habilita sin cuenta, Price IDs y credenciales aprobadas.', acceptance: ['Pago actualiza suscripción correcta.', 'Webhook no altera otra organización.'], status: 'pendiente', evidence: ['src/lib/subscription-plans.ts', 'src/components/plan/BrandPlanSettings.tsx · CTAs actuales'], documentation: `${DOC} §2.4; ${DOC} §6 INT-04; docs/IMPLEMENTATION_ROADMAP.md §3`, tests: 'No ejecutar contra Stripe real sin aprobación.', gaps: 'Falta configuración de producción y autorización.' }),
  r({ id: 'NFR-001', portal: 'Plataforma', module: 'Trazabilidad', title: 'Registrar auditoría transversal de cambios', behavior: 'Registra cambios de entidades más allá del historial de campaña.', rules: 'No se asume audit trail genérico porque no está confirmado.', acceptance: ['Identifica entidad, actor, cambio y fecha.', 'Documenta cobertura por entidad.'], status: 'verificar', evidence: ['src/app/(dashboard)/admin-campaigns/[id]/CampaignDetail.tsx · historial', 'No se identificó tabla genérica confirmada'], documentation: `${DOC} §8 NFR-01`, tests: 'No hay prueba identificada.', gaps: 'Auditoría read-only de schema y rutas antes de diseñar.' }),
]

function StatusBadge({ status }: { status: Status }) {
  const config = STATUS[status]
  return <span className={cn('inline-flex shrink-0 rounded-full px-2.5 py-1 text-[11px] font-semibold ring-1 ring-inset', config.className)}>{config.label}</span>
}

function functionalityOf(item: Requirement): string {
  if (item.module === 'Dashboard') return item.id === 'DASH-006' ? 'Personalización' : 'Indicadores operativos'
  if (item.module === 'Campañas') {
    if (['CAMP-001', 'CAMP-002'].includes(item.id)) return 'Listado y filtros'
    if (['CAMP-003', 'CAMP-004'].includes(item.id)) return 'Creación y visibilidad'
    return 'Ejecución y automatización'
  }
  if (item.module === 'Influencers') {
    if (['INF-001', 'INF-002'].includes(item.id)) return 'Roster'
    if (['INF-003', 'INF-004', 'INF-005'].includes(item.id)) return 'Calidad de datos'
    return 'Ranking'
  }
  if (item.module === 'Campañas de Marca') return item.id === 'BRAND-002' ? 'Acceso a campañas' : 'Creación e invitaciones'
  if (item.module === 'Entregables') return item.id === 'CRE-003' ? 'Consulta de tareas' : 'Entrega de contenido'
  if (item.module === 'Bookings') return item.id === 'BOOK-001' ? 'Agenda operativa' : 'Sincronización de calendario'
  if (item.module === 'CRM') return item.id === 'CRM-001' ? 'Calificación de prospectos' : item.id === 'CRM-002' ? 'Envíos protegidos' : 'Calidad de datos'
  return item.title
}

export function RequirementsClient() {
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<'todos' | Status>('todos')
  const [portal, setPortal] = useState<'todos' | Requirement['portal']>('todos')
  const [module, setModule] = useState('todos')
  const [openNodes, setOpenNodes] = useState<Set<string>>(() => new Set())
  const modules = useMemo(() => Array.from(new Set(REQUIREMENTS.map(item => item.module))).sort(), [])
  const filtered = useMemo(() => {
    const normalized = query.trim().toLocaleLowerCase('es-CL')
    return REQUIREMENTS.filter(item => {
      const searchable = [item.id, item.portal, item.module, item.title, item.behavior, item.rules, item.documentation, ...item.evidence].join(' ').toLocaleLowerCase('es-CL')
      return (!normalized || searchable.includes(normalized)) && (status === 'todos' || item.status === status) && (portal === 'todos' || item.portal === portal) && (module === 'todos' || item.module === module)
    })
  }, [module, portal, query, status])
  const tree = useMemo(() => {
    const groups = new Map<string, Map<string, Requirement[]>>()
    filtered.forEach(item => {
      const functions = groups.get(item.module) ?? new Map<string, Requirement[]>()
      const functionality = functionalityOf(item)
      functions.set(functionality, [...(functions.get(functionality) ?? []), item])
      groups.set(item.module, functions)
    })
    return Array.from(groups.entries())
  }, [filtered])
  const portals = ['Admin', 'Marca', 'Influencer', 'Plataforma'] as const
  const toggle = (key: string) => setOpenNodes(current => {
    const next = new Set(current)
    next.has(key) ? next.delete(key) : next.add(key)
    return next
  })

  return <div className="space-y-5 pb-8">
    <header><p className="text-xs font-bold uppercase tracking-[0.16em] text-violet-600">Portal Admin · fuente funcional</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-gray-950">Requerimientos SCENCE</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-500">Explora capacidades por módulo, funcionalidad y requerimiento. Los detalles se muestran solo al abrir un requerimiento.</p></header>
    <section className="rounded-xl border border-gray-100 bg-white p-3"><div className="flex flex-col gap-3 xl:flex-row"><label className="relative block flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><span className="sr-only">Buscar</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar ID, capacidad, regla, archivo o documento…" className="w-full rounded-lg border border-gray-200 py-2 pl-9 pr-3 text-sm outline-none transition focus:border-violet-400 focus:ring-2 focus:ring-violet-100" /></label><div className="flex flex-wrap gap-2"><label className="flex items-center gap-2 rounded-lg border border-gray-200 px-2.5 text-sm text-gray-600"><Filter className="h-4 w-4 text-gray-400" /><select value={status} onChange={event => setStatus(event.target.value as 'todos' | Status)} className="bg-transparent outline-none"><option value="todos">Estados</option>{(Object.keys(STATUS) as Status[]).map(key => <option key={key} value={key}>{STATUS[key].label}</option>)}</select></label><label className="rounded-lg border border-gray-200 px-2.5 text-sm text-gray-600"><select value={portal} onChange={event => setPortal(event.target.value as 'todos' | Requirement['portal'])} className="h-full bg-transparent outline-none"><option value="todos">Portales</option>{portals.map(name => <option key={name} value={name}>{name}</option>)}</select></label><label className="rounded-lg border border-gray-200 px-2.5 text-sm text-gray-600"><select value={module} onChange={event => setModule(event.target.value)} className="h-full bg-transparent outline-none"><option value="todos">Módulos</option>{modules.map(name => <option key={name} value={name}>{name}</option>)}</select></label></div></div></section>
    <section className="overflow-hidden rounded-xl border border-gray-200 bg-white">
      {tree.map(([moduleName, functions], moduleIndex) => {
        const moduleKey = `module:${moduleName}`
        const moduleOpen = openNodes.has(moduleKey)
        return <div key={moduleName} className={cn(moduleIndex > 0 && 'border-t border-gray-100')}>
          <button onClick={() => toggle(moduleKey)} aria-expanded={moduleOpen} className="flex w-full items-center gap-2.5 px-4 py-3 text-left hover:bg-gray-50"><ChevronRight className={cn('h-4 w-4 shrink-0 text-gray-400 transition-transform', moduleOpen && 'rotate-90')} />{moduleOpen ? <FolderOpen className="h-4 w-4 shrink-0 text-violet-600" /> : <Folder className="h-4 w-4 shrink-0 text-violet-500" />}<span className="flex-1 text-sm font-semibold text-gray-900">{moduleName}</span></button>
          {moduleOpen && <div className="border-t border-gray-100 bg-gray-50/40 py-1">{Array.from(functions.entries()).map(([functionName, requirements]) => {
            const functionKey = `function:${moduleName}:${functionName}`
            const functionOpen = openNodes.has(functionKey)
            return <div key={functionKey} className="ml-5 border-l border-gray-200">
              <button onClick={() => toggle(functionKey)} aria-expanded={functionOpen} className="flex w-full items-center gap-2.5 px-4 py-2.5 text-left hover:bg-violet-50/40"><ChevronRight className={cn('h-3.5 w-3.5 shrink-0 text-gray-400 transition-transform', functionOpen && 'rotate-90')} /><Layers3 className="h-3.5 w-3.5 shrink-0 text-gray-400" /><span className="flex-1 text-sm font-medium text-gray-700">{functionName}</span></button>
              {functionOpen && <div className="ml-5 border-l border-gray-200 pb-1">{requirements.map(item => {
                const requirementKey = `requirement:${item.id}`
                const requirementOpen = openNodes.has(requirementKey)
                return <div key={item.id}><button onClick={() => toggle(requirementKey)} aria-expanded={requirementOpen} className="flex w-full items-center gap-2.5 px-4 py-2 text-left hover:bg-white"><ChevronRight className={cn('h-3.5 w-3.5 shrink-0 text-gray-400 transition-transform', requirementOpen && 'rotate-90')} /><FileText className="h-3.5 w-3.5 shrink-0 text-gray-400" /><span className="min-w-0 flex-1 truncate text-sm text-gray-700"><span className="mr-2 font-mono text-xs font-semibold text-violet-700">{item.id}</span>{item.title}</span><StatusBadge status={item.status} /></button>
                  {requirementOpen && <div className="mx-4 mb-3 ml-10 border-l-2 border-violet-200 pl-4 pr-2 py-2">{item.id === 'DASH-001' && <RequirementPilot />}<div className="grid gap-5 text-sm leading-6 text-gray-600 lg:grid-cols-[minmax(0,1.1fr)_minmax(240px,0.9fr)]"><div className="space-y-4"><div><h3 className="font-semibold text-gray-900">Definición</h3><p>{item.behavior}</p></div><div><h3 className="font-semibold text-gray-900">Reglas de negocio</h3><p>{item.rules}</p></div><div><h3 className="font-semibold text-gray-900">Criterios de aceptación</h3><ul className="mt-1 list-disc space-y-1 pl-5">{item.acceptance.map(criterion => <li key={criterion}>{criterion}</li>)}</ul></div><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-gray-500"><Wrench className="h-4 w-4" /> Pendientes y brechas</p><p className="mt-1">{item.gaps}</p></div></div><aside className="space-y-4"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-gray-500"><ShieldCheck className="h-4 w-4" /> Estado</p><div className="mt-1"><StatusBadge status={item.status} /></div></div><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-gray-500"><FileCode2 className="h-4 w-4" /> Archivos relacionados</p><ul className="mt-1 space-y-1">{item.evidence.map(value => <li key={value} className="break-words text-xs leading-5 text-violet-700">{value}</li>)}</ul></div><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-gray-500"><BookOpenCheck className="h-4 w-4" /> Documentación</p><p className="mt-1 text-xs leading-5 text-gray-600">{item.documentation}</p></div><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-gray-500"><TestTube2 className="h-4 w-4" /> Pruebas</p><p className="mt-1 text-xs leading-5 text-gray-600">{item.tests}</p></div></aside></div></div>}
                </div>
              })}</div>}
            </div>
          })}</div>}
        </div>
      })}
      {!tree.length && <div className="p-10 text-center text-sm text-gray-500">No hay requerimientos que coincidan con los filtros.</div>}
    </section>
  </div>
}
