import { NextRequest, NextResponse } from 'next/server'
import { createServerClient, createAdminClient } from '@/lib/supabase/server'
import { getOrgId } from '@/lib/supabase/ensureOrg'

// ── GET /api/invoices ─────────────────────────────────────────────────────────
export async function GET(request: NextRequest) {
  const supabase = createServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { searchParams } = new URL(request.url)
  const status    = searchParams.get('status')
  const campaignId = searchParams.get('campaign_id')
  const search    = searchParams.get('search')
  const dateFrom  = searchParams.get('date_from')
  const dateTo    = searchParams.get('date_to')
  const page      = parseInt(searchParams.get('page') ?? '1', 10)
  const limit     = parseInt(searchParams.get('limit') ?? '50', 10)

  const admin = createAdminClient()
  const orgId = await getOrgId(user.id, user.user_metadata, admin)

  let query = admin
    .from('invoices')
    .select(`
      *,
      campaign:campaigns (id, name),
      items:invoice_line_items (*)
    `, { count: 'exact' })
    .order('issue_date', { ascending: false })
    .range((page - 1) * limit, page * limit - 1)

  if (orgId)   query = query.eq('organization_id', orgId)
  if (campaignId) query = query.eq('campaign_id', campaignId)
  if (status)  query = query.eq('status', status)
  if (dateFrom) query = query.gte('issue_date', dateFrom)
  if (dateTo)   query = query.lte('issue_date', dateTo)
  if (search)   query = query.ilike('invoice_number', `%${search}%`)

  const { data, error, count } = await query

  if (error) {
    console.error('[GET /api/invoices]', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  // Normalize: extract client_* from metadata for backward compat
  type InvRow = Record<string, unknown>
  const normalized = (data ?? []).map((inv: InvRow) => {
    const meta = (inv.metadata as Record<string, unknown> | null) ?? {}
    return {
      ...inv,
      client_name:    meta.client_name    ?? inv.invoice_number ?? '',
      client_email:   meta.client_email   ?? null,
      client_address: meta.client_address ?? null,
      client_tax_id:  meta.client_tax_id  ?? null,
    }
  })

  return NextResponse.json({ data: normalized, total: count ?? 0, page, limit })
}

// ── POST /api/invoices ────────────────────────────────────────────────────────
export async function POST(request: NextRequest) {
  const supabase = createServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  let body: Record<string, unknown>
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const {
    campaign_id,
    client_name,
    client_email,
    client_address,
    client_tax_id,
    issue_date,
    due_date,
    currency = 'CLP',
    tax_rate = 0,
    notes,
    items = [],
    organization_id,
  } = body as Record<string, unknown>

  if (!client_name || !issue_date || !due_date) {
    return NextResponse.json(
      { error: 'client_name, issue_date and due_date are required' },
      { status: 422 }
    )
  }

  const admin = createAdminClient()
  const orgId = (organization_id as string) ?? await getOrgId(user.id, user.user_metadata, admin)

  // Subtotal from items
  const itemsArr = items as Array<{ quantity: number; unit_price: number }>
  const subtotal = itemsArr.reduce((s, i) => s + (i.quantity ?? 1) * (i.unit_price ?? 0), 0)
  const taxAmount = subtotal * ((tax_rate as number) / 100)
  const total = subtotal + taxAmount

  // Create invoice (invoice_number auto-generated by DB trigger)
  // client_* columns don't exist in DB schema — store in metadata JSONB
  const { data: invoice, error: invErr } = await admin
    .from('invoices')
    .insert({
      organization_id: orgId,
      campaign_id: campaign_id ?? null,
      issue_date,
      due_date,
      currency,
      subtotal,
      tax_rate,
      tax_amount: taxAmount,
      total,
      status: 'draft',
      notes: notes ?? null,
      issued_by: user.id,  // correct column name
      metadata: {
        client_name:    client_name ?? null,
        client_email:   client_email ?? null,
        client_address: client_address ?? null,
        client_tax_id:  client_tax_id ?? null,
      },
    })
    .select()
    .single()

  if (invErr) {
    console.error('[POST /api/invoices] invoice', invErr)
    return NextResponse.json({ error: invErr.message }, { status: 500 })
  }

  // Insert items if provided
  if (itemsArr.length > 0) {
    const { error: itemsErr } = await admin
      .from('invoice_line_items')
      .insert(
        itemsArr.map((item, idx) => ({
          invoice_id:  invoice.id,
          description: (item as Record<string, unknown>).description ?? `Línea ${idx + 1}`,
          quantity:    item.quantity ?? 1,
          unit_price:  item.unit_price ?? 0,
          amount:      (item.quantity ?? 1) * (item.unit_price ?? 0),  // correct column name
          currency:    currency as string ?? 'CLP',
        }))
      )

    if (itemsErr) {
      console.error('[POST /api/invoices] items', itemsErr)
      // Non-fatal — invoice exists, items failed
    }
  }

  // Fetch full invoice with items
  const { data } = await admin
    .from('invoices')
    .select('*, items:invoice_line_items(*)')
    .eq('id', invoice.id)
    .single()

  return NextResponse.json({ data }, { status: 201 })
}
