'use client'

import { useCallback, useEffect, useState } from 'react'
import { FileSignature, Loader2, Plus } from 'lucide-react'
import { toast } from 'sonner'

type Template = { id: string; name: string; document_type?: string; language?: string }
type Document = { id: string; title: string; status: string; signer_name: string | null; signer_email: string | null; signed_at: string | null; due_at: string; created_at: string }

export function BrandDocumentsAdmin({ brandId }: { brandId: string }) {
  const [documents, setDocuments] = useState<Document[]>([]); const [templates, setTemplates] = useState<Template[]>([]); const [templateId, setTemplateId] = useState(''); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { const [docsRes, templatesRes] = await Promise.all([fetch(`/api/brands/${brandId}/documents`), fetch('/api/contracts/templates')]); const docs = await docsRes.json(); const templates = await templatesRes.json(); if (!docsRes.ok) throw new Error(docs.error ?? 'No se pudieron cargar documentos'); setDocuments(docs.data ?? []); const available = templates.data ?? []; setTemplates(available); setTemplateId(current => current || available.find((t: Template) => t.document_type === 'nda' || /nda/i.test(t.name))?.id || available[0]?.id || '') } catch (e) { toast.error((e as Error).message) } finally { setLoading(false) } }, [brandId])
  useEffect(() => { load() }, [load])
  const create = async () => { if (!templateId) return; setCreating(true); try { const res = await fetch(`/api/brands/${brandId}/documents`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ template_id: templateId }) }); const json = await res.json(); if (!res.ok) throw new Error(json.error ?? 'No se pudo enviar el documento'); toast.success('Documento enviado a la Marca'); load() } catch (e) { toast.error((e as Error).message) } finally { setCreating(false) } }
  if (loading) return <div className="py-12 flex justify-center"><Loader2 className="animate-spin text-violet-600" /></div>
  return <div className="space-y-5"><div className="card p-5"><h2 className="font-bold text-gray-900">Enviar NDA a firma</h2><p className="text-sm text-gray-500 mt-1">Se enviará un email inmediato a la Marca. Tendrá 7 días para completar los datos del representante y firmar.</p><div className="flex flex-col sm:flex-row gap-3 mt-4"><select className="input-base flex-1" value={templateId} onChange={e => setTemplateId(e.target.value)}><option value="">Selecciona un template</option>{templates.map(t => <option key={t.id} value={t.id}>{t.name} · {(t.language ?? 'es').toUpperCase()}</option>)}</select><button onClick={create} disabled={!templateId || creating} className="inline-flex items-center justify-center gap-2 bg-violet-600 text-white px-4 rounded-lg text-sm font-semibold disabled:opacity-50">{creating ? 'Enviando…' : <><Plus className="h-4 w-4" />Enviar a firma</>}</button></div></div><div className="card overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold text-gray-900">Historial de documentos</h2></div>{documents.length === 0 ? <p className="p-6 text-sm text-gray-400">Aún no se han enviado documentos a esta Marca.</p> : <div className="divide-y">{documents.map(d => <div key={d.id} className="p-4 flex justify-between gap-4"><div><p className="font-medium text-gray-900">{d.title}</p><p className="text-xs text-gray-400">Enviado a {d.signer_email ?? 'sin email'} · vence {new Date(d.due_at).toLocaleDateString('es-CL')}</p></div><div className="text-right text-sm">{d.status === 'signed' ? <><p className="text-emerald-700 font-semibold">Firmado</p><p className="text-xs text-gray-400">{d.signer_name} · {d.signed_at && new Date(d.signed_at).toLocaleDateString('es-CL')}</p></> : <p className="text-amber-700 font-semibold">Pendiente de firma</p>}</div></div>)}</div>}</div></div>
}
