-- ============================================================================
-- Locations — Seed Chile: 1 país, 16 regiones, 346 comunas.
-- Fuente: src/lib/communes-chile.ts (BCN). Generado, no editar a mano.
-- Sin ciudades: city es opcional y se agrega solo cuando aporta.
-- Idempotente: inserta solo lo que falta (unicidad por padre+nivel+nombre normalizado).
-- ============================================================================

INSERT INTO public.locations (level, name, parent_id)
SELECT 'country', 'Chile', NULL
WHERE NOT EXISTS (SELECT 1 FROM public.locations WHERE level = 'country' AND public.locations_norm(name) = 'chile');

WITH c AS (SELECT id FROM public.locations WHERE level = 'country' AND public.locations_norm(name) = 'chile')
INSERT INTO public.locations (level, name, parent_id)
SELECT 'region', r.name, c.id
FROM c, (VALUES
  ('Arica y Parinacota'),
  ('Tarapacá'),
  ('Antofagasta'),
  ('Atacama'),
  ('Coquimbo'),
  ('Valparaíso'),
  ('O''Higgins'),
  ('Maule'),
  ('Ñuble'),
  ('Biobío'),
  ('La Araucanía'),
  ('Los Ríos'),
  ('Los Lagos'),
  ('Aysén'),
  ('Magallanes'),
  ('Región Metropolitana')
) AS r(name)
WHERE NOT EXISTS (
  SELECT 1 FROM public.locations x
  WHERE x.parent_id = c.id AND x.level = 'region' AND public.locations_norm(x.name) = public.locations_norm(r.name)
);

WITH c AS (SELECT id FROM public.locations WHERE level = 'country' AND public.locations_norm(name) = 'chile'),
     regions AS (
       SELECT x.id, x.name FROM public.locations x, c
       WHERE x.parent_id = c.id AND x.level = 'region'
     ),
     data(region, commune) AS (VALUES
  ('Arica y Parinacota', 'Arica'),
  ('Arica y Parinacota', 'Camarones'),
  ('Arica y Parinacota', 'Putre'),
  ('Arica y Parinacota', 'General Lagos'),
  ('Tarapacá', 'Alto Hospicio'),
  ('Tarapacá', 'Iquique'),
  ('Tarapacá', 'Huara'),
  ('Tarapacá', 'Camiña'),
  ('Tarapacá', 'Colchane'),
  ('Tarapacá', 'Pica'),
  ('Tarapacá', 'Pozo Almonte'),
  ('Antofagasta', 'Tocopilla'),
  ('Antofagasta', 'María Elena'),
  ('Antofagasta', 'Calama'),
  ('Antofagasta', 'Ollagüe'),
  ('Antofagasta', 'San Pedro de Atacama'),
  ('Antofagasta', 'Antofagasta'),
  ('Antofagasta', 'Mejillones'),
  ('Antofagasta', 'Sierra Gorda'),
  ('Antofagasta', 'Taltal'),
  ('Atacama', 'Chañaral'),
  ('Atacama', 'Diego de Almagro'),
  ('Atacama', 'Copiapó'),
  ('Atacama', 'Caldera'),
  ('Atacama', 'Tierra Amarilla'),
  ('Atacama', 'Vallenar'),
  ('Atacama', 'Freirina'),
  ('Atacama', 'Huasco'),
  ('Atacama', 'Alto del Carmen'),
  ('Coquimbo', 'La Serena'),
  ('Coquimbo', 'La Higuera'),
  ('Coquimbo', 'Coquimbo'),
  ('Coquimbo', 'Andacollo'),
  ('Coquimbo', 'Vicuña'),
  ('Coquimbo', 'Paihuano'),
  ('Coquimbo', 'Ovalle'),
  ('Coquimbo', 'Río Hurtado'),
  ('Coquimbo', 'Monte Patria'),
  ('Coquimbo', 'Combarbalá'),
  ('Coquimbo', 'Punitaqui'),
  ('Coquimbo', 'Illapel'),
  ('Coquimbo', 'Salamanca'),
  ('Coquimbo', 'Los Vilos'),
  ('Coquimbo', 'Canela'),
  ('Valparaíso', 'La Ligua'),
  ('Valparaíso', 'Petorca'),
  ('Valparaíso', 'Cabildo'),
  ('Valparaíso', 'Zapallar'),
  ('Valparaíso', 'Papudo'),
  ('Valparaíso', 'Los Andes'),
  ('Valparaíso', 'San Esteban'),
  ('Valparaíso', 'Calle Larga'),
  ('Valparaíso', 'Rinconada'),
  ('Valparaíso', 'San Felipe'),
  ('Valparaíso', 'Putaendo'),
  ('Valparaíso', 'Santa María'),
  ('Valparaíso', 'Panquehue'),
  ('Valparaíso', 'Llay-Llay'),
  ('Valparaíso', 'Catemu'),
  ('Valparaíso', 'Quillota'),
  ('Valparaíso', 'La Cruz'),
  ('Valparaíso', 'La Calera'),
  ('Valparaíso', 'Nogales'),
  ('Valparaíso', 'Hijuelas'),
  ('Valparaíso', 'Limache'),
  ('Valparaíso', 'Olmué'),
  ('Valparaíso', 'Valparaíso'),
  ('Valparaíso', 'Viña del Mar'),
  ('Valparaíso', 'Quintero'),
  ('Valparaíso', 'Puchuncaví'),
  ('Valparaíso', 'Quilpué'),
  ('Valparaíso', 'Villa Alemana'),
  ('Valparaíso', 'Casablanca'),
  ('Valparaíso', 'Concón'),
  ('Valparaíso', 'Juan Fernández'),
  ('Valparaíso', 'San Antonio'),
  ('Valparaíso', 'Cartagena'),
  ('Valparaíso', 'El Tabo'),
  ('Valparaíso', 'El Quisco'),
  ('Valparaíso', 'Algarrobo'),
  ('Valparaíso', 'Santo Domingo'),
  ('Valparaíso', 'Isla de Pascua'),
  ('O''Higgins', 'Rancagua'),
  ('O''Higgins', 'Graneros'),
  ('O''Higgins', 'Mostazal'),
  ('O''Higgins', 'Codegua'),
  ('O''Higgins', 'Machalí'),
  ('O''Higgins', 'Olivar'),
  ('O''Higgins', 'Requínoa'),
  ('O''Higgins', 'Rengo'),
  ('O''Higgins', 'Malloa'),
  ('O''Higgins', 'Quinta de Tilcoco'),
  ('O''Higgins', 'San Vicente de Tagua Tagua'),
  ('O''Higgins', 'Pichidegua'),
  ('O''Higgins', 'Peumo'),
  ('O''Higgins', 'Coltauco'),
  ('O''Higgins', 'Coinco'),
  ('O''Higgins', 'Doñihue'),
  ('O''Higgins', 'Las Cabras'),
  ('O''Higgins', 'San Fernando'),
  ('O''Higgins', 'Chimbarongo'),
  ('O''Higgins', 'Placilla'),
  ('O''Higgins', 'Nancagua'),
  ('O''Higgins', 'Chépica'),
  ('O''Higgins', 'Santa Cruz'),
  ('O''Higgins', 'Lolol'),
  ('O''Higgins', 'Pumanque'),
  ('O''Higgins', 'Palmilla'),
  ('O''Higgins', 'Peralillo'),
  ('O''Higgins', 'Pichilemu'),
  ('O''Higgins', 'Navidad'),
  ('O''Higgins', 'Litueche'),
  ('O''Higgins', 'La Estrella'),
  ('O''Higgins', 'Marchihue'),
  ('O''Higgins', 'Paredones'),
  ('Maule', 'Curicó'),
  ('Maule', 'Teno'),
  ('Maule', 'Romeral'),
  ('Maule', 'Molina'),
  ('Maule', 'Sagrada Familia'),
  ('Maule', 'Hualañé'),
  ('Maule', 'Licantén'),
  ('Maule', 'Vichuquén'),
  ('Maule', 'Rauco'),
  ('Maule', 'Talca'),
  ('Maule', 'Pelarco'),
  ('Maule', 'Río Claro'),
  ('Maule', 'San Clemente'),
  ('Maule', 'Maule'),
  ('Maule', 'San Rafael'),
  ('Maule', 'Empedrado'),
  ('Maule', 'Pencahue'),
  ('Maule', 'Constitución'),
  ('Maule', 'Curepto'),
  ('Maule', 'Linares'),
  ('Maule', 'Yerbas Buenas'),
  ('Maule', 'Colbún'),
  ('Maule', 'Longaví'),
  ('Maule', 'Parral'),
  ('Maule', 'Retiro'),
  ('Maule', 'Villa Alegre'),
  ('Maule', 'San Javier'),
  ('Maule', 'Cauquenes'),
  ('Maule', 'Pelluhue'),
  ('Maule', 'Chanco'),
  ('Ñuble', 'Chillán'),
  ('Ñuble', 'San Carlos'),
  ('Ñuble', 'Ñiquén'),
  ('Ñuble', 'San Fabián'),
  ('Ñuble', 'Coihueco'),
  ('Ñuble', 'Pinto'),
  ('Ñuble', 'San Ignacio'),
  ('Ñuble', 'El Carmen'),
  ('Ñuble', 'Yungay'),
  ('Ñuble', 'Pemuco'),
  ('Ñuble', 'Bulnes'),
  ('Ñuble', 'Quillón'),
  ('Ñuble', 'Ránquil'),
  ('Ñuble', 'Portezuelo'),
  ('Ñuble', 'Coelemu'),
  ('Ñuble', 'Trehuaco'),
  ('Ñuble', 'Cobquecura'),
  ('Ñuble', 'Quirihue'),
  ('Ñuble', 'Ninhue'),
  ('Ñuble', 'San Nicolás'),
  ('Ñuble', 'Chillán Viejo'),
  ('Biobío', 'Los Ángeles'),
  ('Biobío', 'Cabrero'),
  ('Biobío', 'Tucapel'),
  ('Biobío', 'Antuco'),
  ('Biobío', 'Quilleco'),
  ('Biobío', 'Santa Bárbara'),
  ('Biobío', 'Quilaco'),
  ('Biobío', 'Mulchén'),
  ('Biobío', 'Negrete'),
  ('Biobío', 'Nacimiento'),
  ('Biobío', 'Laja'),
  ('Biobío', 'San Rosendo'),
  ('Biobío', 'Yumbel'),
  ('Biobío', 'Alto Biobío'),
  ('Biobío', 'Concepción'),
  ('Biobío', 'Talcahuano'),
  ('Biobío', 'Penco'),
  ('Biobío', 'Tomé'),
  ('Biobío', 'Florida'),
  ('Biobío', 'Hualpén'),
  ('Biobío', 'Hualqui'),
  ('Biobío', 'Santa Juana'),
  ('Biobío', 'Lota'),
  ('Biobío', 'Coronel'),
  ('Biobío', 'San Pedro de la Paz'),
  ('Biobío', 'Chiguayante'),
  ('Biobío', 'Lebu'),
  ('Biobío', 'Arauco'),
  ('Biobío', 'Curanilahue'),
  ('Biobío', 'Los Álamos'),
  ('Biobío', 'Cañete'),
  ('Biobío', 'Contulmo'),
  ('Biobío', 'Tirúa'),
  ('La Araucanía', 'Angol'),
  ('La Araucanía', 'Renaico'),
  ('La Araucanía', 'Collipulli'),
  ('La Araucanía', 'Lonquimay'),
  ('La Araucanía', 'Curacautín'),
  ('La Araucanía', 'Ercilla'),
  ('La Araucanía', 'Victoria'),
  ('La Araucanía', 'Traiguén'),
  ('La Araucanía', 'Lumaco'),
  ('La Araucanía', 'Purén'),
  ('La Araucanía', 'Los Sauces'),
  ('La Araucanía', 'Temuco'),
  ('La Araucanía', 'Lautaro'),
  ('La Araucanía', 'Perquenco'),
  ('La Araucanía', 'Vilcún'),
  ('La Araucanía', 'Cholchol'),
  ('La Araucanía', 'Cunco'),
  ('La Araucanía', 'Melipeuco'),
  ('La Araucanía', 'Curarrehue'),
  ('La Araucanía', 'Pucón'),
  ('La Araucanía', 'Villarrica'),
  ('La Araucanía', 'Freire'),
  ('La Araucanía', 'Pitrufquén'),
  ('La Araucanía', 'Gorbea'),
  ('La Araucanía', 'Loncoche'),
  ('La Araucanía', 'Toltén'),
  ('La Araucanía', 'Teodoro Schmidt'),
  ('La Araucanía', 'Saavedra'),
  ('La Araucanía', 'Carahue'),
  ('La Araucanía', 'Nueva Imperial'),
  ('La Araucanía', 'Galvarino'),
  ('La Araucanía', 'Padre Las Casas'),
  ('Los Ríos', 'Valdivia'),
  ('Los Ríos', 'Mariquina'),
  ('Los Ríos', 'Lanco'),
  ('Los Ríos', 'Máfil'),
  ('Los Ríos', 'Corral'),
  ('Los Ríos', 'Los Lagos'),
  ('Los Ríos', 'Panguipulli'),
  ('Los Ríos', 'Paillaco'),
  ('Los Ríos', 'La Unión'),
  ('Los Ríos', 'Futrono'),
  ('Los Ríos', 'Río Bueno'),
  ('Los Ríos', 'Lago Ranco'),
  ('Los Lagos', 'Osorno'),
  ('Los Lagos', 'San Pablo'),
  ('Los Lagos', 'Puyehue'),
  ('Los Lagos', 'Puerto Octay'),
  ('Los Lagos', 'Purranque'),
  ('Los Lagos', 'Río Negro'),
  ('Los Lagos', 'San Juan de la Costa'),
  ('Los Lagos', 'Puerto Montt'),
  ('Los Lagos', 'Puerto Varas'),
  ('Los Lagos', 'Cochamó'),
  ('Los Lagos', 'Calbuco'),
  ('Los Lagos', 'Maullín'),
  ('Los Lagos', 'Los Muermos'),
  ('Los Lagos', 'Fresia'),
  ('Los Lagos', 'Llanquihue'),
  ('Los Lagos', 'Frutillar'),
  ('Los Lagos', 'Castro'),
  ('Los Lagos', 'Ancud'),
  ('Los Lagos', 'Quemchi'),
  ('Los Lagos', 'Dalcahue'),
  ('Los Lagos', 'Curaco de Vélez'),
  ('Los Lagos', 'Quinchao'),
  ('Los Lagos', 'Puqueldón'),
  ('Los Lagos', 'Chonchi'),
  ('Los Lagos', 'Queilén'),
  ('Los Lagos', 'Quellón'),
  ('Los Lagos', 'Chaitén'),
  ('Los Lagos', 'Hualaihué'),
  ('Los Lagos', 'Futaleufú'),
  ('Los Lagos', 'Palena'),
  ('Aysén', 'Coyhaique'),
  ('Aysén', 'Lago Verde'),
  ('Aysén', 'Aysén'),
  ('Aysén', 'Cisnes'),
  ('Aysén', 'Guaitecas'),
  ('Aysén', 'Chile Chico'),
  ('Aysén', 'Río Ibáñez'),
  ('Aysén', 'Cochrane'),
  ('Aysén', 'O''Higgins'),
  ('Aysén', 'Tortel'),
  ('Magallanes', 'Natales'),
  ('Magallanes', 'Torres del Paine'),
  ('Magallanes', 'Punta Arenas'),
  ('Magallanes', 'Río Verde'),
  ('Magallanes', 'Laguna Blanca'),
  ('Magallanes', 'San Gregorio'),
  ('Magallanes', 'Porvenir'),
  ('Magallanes', 'Primavera'),
  ('Magallanes', 'Timaukel'),
  ('Magallanes', 'Cabo de Hornos'),
  ('Magallanes', 'Antártica'),
  ('Región Metropolitana', 'Santiago'),
  ('Región Metropolitana', 'Independencia'),
  ('Región Metropolitana', 'Conchalí'),
  ('Región Metropolitana', 'Huechuraba'),
  ('Región Metropolitana', 'Recoleta'),
  ('Región Metropolitana', 'Providencia'),
  ('Región Metropolitana', 'Vitacura'),
  ('Región Metropolitana', 'Lo Barnechea'),
  ('Región Metropolitana', 'Las Condes'),
  ('Región Metropolitana', 'Ñuñoa'),
  ('Región Metropolitana', 'La Reina'),
  ('Región Metropolitana', 'Macul'),
  ('Región Metropolitana', 'Peñalolén'),
  ('Región Metropolitana', 'La Florida'),
  ('Región Metropolitana', 'San Joaquín'),
  ('Región Metropolitana', 'La Granja'),
  ('Región Metropolitana', 'La Pintana'),
  ('Región Metropolitana', 'San Ramón'),
  ('Región Metropolitana', 'San Miguel'),
  ('Región Metropolitana', 'La Cisterna'),
  ('Región Metropolitana', 'El Bosque'),
  ('Región Metropolitana', 'Pedro Aguirre Cerda'),
  ('Región Metropolitana', 'Lo Espejo'),
  ('Región Metropolitana', 'Estación Central'),
  ('Región Metropolitana', 'Cerrillos'),
  ('Región Metropolitana', 'Maipú'),
  ('Región Metropolitana', 'Quinta Normal'),
  ('Región Metropolitana', 'Lo Prado'),
  ('Región Metropolitana', 'Pudahuel'),
  ('Región Metropolitana', 'Cerro Navia'),
  ('Región Metropolitana', 'Renca'),
  ('Región Metropolitana', 'Quilicura'),
  ('Región Metropolitana', 'Colina'),
  ('Región Metropolitana', 'Lampa'),
  ('Región Metropolitana', 'Tiltil'),
  ('Región Metropolitana', 'Puente Alto'),
  ('Región Metropolitana', 'San José de Maipo'),
  ('Región Metropolitana', 'Pirque'),
  ('Región Metropolitana', 'San Bernardo'),
  ('Región Metropolitana', 'Buin'),
  ('Región Metropolitana', 'Paine'),
  ('Región Metropolitana', 'Calera de Tango'),
  ('Región Metropolitana', 'Melipilla'),
  ('Región Metropolitana', 'María Pinto'),
  ('Región Metropolitana', 'Curacaví'),
  ('Región Metropolitana', 'Alhué'),
  ('Región Metropolitana', 'San Pedro'),
  ('Región Metropolitana', 'Talagante'),
  ('Región Metropolitana', 'Peñaflor'),
  ('Región Metropolitana', 'Isla de Maipo'),
  ('Región Metropolitana', 'El Monte'),
  ('Región Metropolitana', 'Padre Hurtado')
     )
INSERT INTO public.locations (level, name, parent_id)
SELECT 'commune', d.commune, rg.id
FROM data d
JOIN regions rg ON public.locations_norm(rg.name) = public.locations_norm(d.region)
WHERE NOT EXISTS (
  -- la comuna ya existe en esta región (directa o bajo una ciudad)
  SELECT 1 FROM public.locations cm
  JOIN public.locations p ON p.id = cm.parent_id
  WHERE cm.level = 'commune'
    AND public.locations_norm(cm.name) = public.locations_norm(d.commune)
    AND (CASE p.level WHEN 'region' THEN p.id ELSE p.parent_id END) = rg.id
);

-- Backfill de places existentes: asignar comuna cuando el texto legacy calza
-- EXACTO (normalizado) con una comuna oficial. No se inventa nada: un place
-- sin comuna reconocible queda con parent_id NULL ("sin ubicar") y el trigger
-- exigirá asignarla en su próxima edición.
-- Solo si las columnas legacy aún existen (re-ejecutable tras 20261004230200).
DO $backfill$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = 'locations' AND column_name = 'city') THEN
    EXECUTE $sql$
UPDATE public.locations pl
SET parent_id = cm.id
FROM public.locations cm
WHERE pl.level = 'place'
  AND pl.parent_id IS NULL
  AND cm.level = 'commune'
  AND public.locations_norm(cm.name) = public.locations_norm(pl.city)
  AND (SELECT count(*) FROM public.locations c2
       WHERE c2.level = 'commune' AND public.locations_norm(c2.name) = public.locations_norm(pl.city)) = 1
    $sql$;
  END IF;
END $backfill$;

DO $$
DECLARE n_reg int; n_com int;
BEGIN
  SELECT count(*) INTO n_reg FROM public.locations WHERE level = 'region';
  SELECT count(*) INTO n_com FROM public.locations WHERE level = 'commune';
  IF n_reg < 16 OR n_com < 346 THEN
    RAISE EXCEPTION 'Seed Chile incompleto: % regiones, % comunas', n_reg, n_com;
  END IF;
END $$;
